spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:8089
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true