spring:
  application:
    name: hystrix-turbine
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
turbine:
  appConfig: node1,node2,node3
#指定集群
  clusterConfig: default
  clusterNameExpression: new String("default")